# Welcome to Jekyll!
#

# Site settings
title: 1108 Ossington Ave
description: |
  'The Oz'
owner: Jimmy # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: morrisondano@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://neurosponge.com/theoz" # the base hostname & protocol for your site
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
